version: "3.9"
services:
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - data_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: matkhau123
    ports:
      - "3306:3306"
      - "33060:33060"
  web:
    build: .
    command: bash -c "sleep 10 && rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/demo_docker
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  data_db: