default: &default
  adapter: mysql2
  host: db
  username: root
  password: matkhau123
  pool: 5

development:
  <<: *default
  database: demo_docker_development


test:
  <<: *default
  database: demo_docker_test